export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const INPUT_TEXT = "INPUT_TEXT";
export const COMMENT_CREATE = "COMMENT_CREATE";
export const COMMENT_UPDATE = "COMMENT_UPDATE";
export const COMMENT_DELETE = "COMMENT_DELETE";

export const COMMENT_LOAD = "COMMENT_LOAD";
export const COMMENT_DISPLAY_ON = "COMMENT_DISPLAY_ON";
export const COMMENT_DISPLAY_OFF = "COMMENT_DISPLAY_OFF";

export const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
export const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";
